<?php

class IndexController extends ControllerBase
{

    public function indexAction()
    {
    //echo 'here';exit;

// This file is generated by Composer
        require_once '../vendor/autoload.php';

        $client = new \Github\Client();
        $repositories = $client->api('user')->repositories('ornicar');
        var_dump($repositories);
       exit;

    }

}

